Repository MicrosoftDocs/BusinessApplication-ReleaseNotes, pull requests merged in 2018-05, with the labels that each got.

#13 Shelly ha toc 0506
  articles/Spring18/data-integration/whats-new-data-integration.md
  articles/Spring18/data-protection-security.md
  articles/Spring18/finance-insights/credit-collections-overview.md
  articles/Spring18/general-data-protection-regulation.md
  articles/Spring18/release-overview.md
  articles/Spring18/resources-manage-gdpr-compliance-organization.md
  articles/TOC.md
  articles/index.md
Labels: ready for review

#20 Jc remove payroll
  articles/Spring18/change-history.md
  articles/Spring18/dynamics365-talent/whats-new-talent-core-hr.md
Labels: copy edited, cp reviewed, go live ready, ready for review

#26 Porting updates by PM for the Business Intelligence Platform section …
  articles/Spring18/change-history.md
  articles/Spring18/power-bi/whats-new-business-intelligence-platform.md
Labels: copy edited, cp reviewed

#27 MSE Social Insights
  articles/Spring18/microsoft-social-engagement/compliance-accessibility-enhancements.md
  articles/Spring18/microsoft-social-engagement/social-insights.md
  articles/TOC.md
Labels: copy edited, cp reviewed

#31 8.0 on premise not in the spring timeframe
  articles/Spring18/dynamics365-finance-operations/on-premises-deployment-updates.md
Labels: copy edited, cp reviewed, go live ready, ready for review

#25 Add mid-may features
  articles/April18/microsoft-flow/error-details-analytics.md
  articles/April18/microsoft-flow/media/error-details-analytics-chart.png
  articles/April18/microsoft-flow/media/error-details-analytics-entry.png
  articles/April18/microsoft-flow/media/share-office365-flow-properties.png
  articles/April18/microsoft-flow/media/share-office365-owners.png
  articles/April18/microsoft-flow/media/share-office365-team-flows.png
  articles/April18/microsoft-flow/media/sharepoint-connector-improvements.png
  articles/April18/microsoft-flow/media/sharepoint-own-flows-owners.png
  articles/April18/microsoft-flow/media/sharepoint-own-flows-properties.png
  articles/April18/microsoft-flow/media/sharepoint-own-flows-run-flow.png
  articles/April18/microsoft-flow/media/sharepoint-own-flows-run-only.png
  articles/April18/microsoft-flow/repair-recommendations-sent-email-failed-flows.md
  articles/April18/microsoft-flow/share-with-o365-groups.md
  articles/April18/microsoft-flow/sharepoint-connector-improvements.md
  articles/April18/microsoft-flow/sharepoint-lists-libraries.md
  articles/April18/microsoft-flow/whats-new-flow.md
  articles/April18/toc.md
Labels: cp reviewed, ready for review

#34 Correct the link of Enhanced configurability
  articles/April18/dynamics365-finance-operations/whats-new-finance-operations.md
Labels: copy edited, cp reviewed, go live ready, ready for review

#42 Mid-may additions for Flows
  articles/April18/change-history.md
Labels: copy edited, cp reviewed

#44 Fixed dates for Power BI and Flow sections
  articles/April18/change-history.md
Labels: copy edited, cp reviewed

#62 Late breaking changes for Power BI Embedded
  articles/April18/TOC.md
  articles/April18/change-history.md
  articles/April18/power-bi/embedded/available-german-datacenters.md
  articles/April18/power-bi/embedded/export-pdf.md
  articles/April18/power-bi/embedded/export-powerpoint.md
  articles/April18/power-bi/whats-new-business-intelligence-platform.md
Labels: copy edited, cp reviewed
